### ISSUE TITLE
Branch trigger not working when trying to push changes to branch

### ISSUE THREAD

**Issue by JerBear70** [jenkinsci/bitbucket-push-and-pull-request-plugin#189] opened 2021-06-30 16:20 UTC
I have upgrade the plugin to the latest version (2.7.2)  and am unable to get the bppr trigger to work when pushing changes to a branch.  The SCM trigger fires with no issues but am not able to get a match on the trigger filter when specifying refs/heads/SIF-1089.  I have tried this various ways with trying to specify this branch and nothing has worked.  Attached is what the Jenkins Config looks like for the trigger.  

![JenkinsConfig](https://user-images.githubusercontent.com/51175905/123994728-e1af2c00-d98a-11eb-8a75-dfd199aceadd.jpg)

Ultimately we want to get this working to push for any changes off of a branch with "SIF-" in it.  But first just need to get it to work in general.

We have used this plugin with Pull Request for a long time with no issues.  First time trying with Push. 
-----------------------------------------------------
I have also attached the log file after adding io.jenkins.plugins.bitbucketpushandpullrequest as a Logger for Bitbucket.
This is the log right after I pushed a change to the SIF-1089 branch.
[Jenkins_BitBucketLog.txt](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/files/6742465/Jenkins_BitBucketLog.txt)

**Comment by JerBear70** [comment] 2021-07-06 18:09
hi cdelmonte-zg - is there anything that you have found on this?  We are at a stand-still with implementation of our project until we can get this piece working correctly.

**Comment by JerBear70** [comment] 2021-07-08 17:46
Anything on this yet?  Need any other information.  I have tried many different ways and just can't get the filter to pick trigger to filter correctly.

**Comment by FBNitro** [comment] 2021-09-22 18:16
I am also looking for an update on this ticket.  I've got the PR Build working on PR create, but when I push changes into the branch it does not fire the build again.

**Comment by derekatkins** [comment] 2021-11-12 22:35
I (think) I am having the same issue. 

When I open a PR it fires off a build of the PR working branch.  It will also fire off a build if I push updates to the working branch of the PR.  Moreover, it will build master once I merge the PR.

HOWEVER, I want to fire off a build any time someone makes a push directly to a branch, e.g., master, so I set it up to do a PUSH build.  I get the webhook call from bitbucket but no build is fired off on Jenkins.

If I leave the "Allowed Branches" empty it *will* fire off a build on a direct push to master, but it will also fire off a build on any commit to any branch, which is not what I want.  So the issue is clearly that I'm not setting the Allowed Branches correctly.  I have tried:
 * refs/heads/master
 * origin/master 
 * */master

I would really like to get this solved (although I supposed I can probably solve it by using both this plugin and the "Bitbucket" plugin at different URLs -- however I'm not sure if I'll get two builds during a Merge).

**Comment by derekatkins** [comment] 2021-11-14 14:06
Just a quick update -- I created a logger for `io.jenkins.plugins.bitbucketpushandpullrequest` at level `FINEST` and noticed it was saying that the active branch was "master", so I reconfigured the PUSH setting of Allowed Branches to "master" (not origin/master, not */master) and viola, it actually worked.  I made a push directly to master and the branch built!  I still need to test PRs again to make sure it wont build other branches, but right now I think this is working.

@JerBear70 -- have you run a full log?  When you push, what do you see for "The branchName in action"?  I feel like the documentation is not 100% correct; I was expecting the branch to be "origin/master", but it's not, it's just "master".

@FBNitro -- I have pushes to a PR branch working fine.  How do you have the plugin configured?  And how do you have your WebHook configured?  I have the plugin configured for Created/Updated/Merged (three trigger rules). all with empty branch configs, and the Webhook is set to trigger on Repo Push, and PR Created, Updated, Merged.

**Closed** 2024-10-14 14:18 UTC
Labels: investigating
